apiVersion: v1
kind: Pod
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  containers:
  - command:
    env:
    - name: HOSTNAME
      value: registry.sparta.redhat.dev.shipyard.blackpearl.us
    - name: container
      value: podman
    - name: GITLAB
    - name: GITLAB_OMNIBUS_CONFIG
      value: |
        external_url 'http://registry.sparta.redhat.dev.shipyard.blackpearl.us/';
        gitlab_rails['lfs_enabled'] = true;
    image: docker.io/gitlab/gitlab-ce:13.7.0-ce-0
    name: gitlab
    ports:
    - containerPort: 443
      hostPort: 443
      protocol: TCP
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 22
      hostPort: 22
      protocol: TCP
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities: {}
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    volumeMounts:
    - mountPath: /etc/gitlab
      name: srv-gitlab-config
    - mountPath: /var/log/gitlab
      name: srv-gitlab-logs
    - mountPath: /var/opt/gitlab
      name: srv-gitlab-data
    workingDir: /
  volumes:
  - hostPath:
      path: /srv/gitlab/config
      type: Directory
    name: srv-gitlab-config
  - hostPath:
      path: /srv/gitlab/logs
      type: Directory
    name: srv-gitlab-logs
  - hostPath:
      path: /srv/gitlab/data
      type: Directory
    name: srv-gitlab-data
