---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRESQL_ADMIN_PASSWORD: redhatredhat
  POSTGRESQL_DATABASE: postgresdb
  POSTGRESQL_USER: postgresadmin
  POSTGRESQL_PASSWORD: admin123
