---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: registry.sparta.redhat.dev.shipyard.blackpearl.us:5000/rhel8/postgresql-96
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
          envFrom:
            - configMapRef:
                name: postgres-config
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
