apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./resources/deployment.yaml
  - ./resources/pv.yaml
  - ./resources/pvc.yaml
  - ./resources/service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: postgres-config
    literals:
      - POSTGRESQL_ADMIN_PASSWORD=redhatredhat
      - POSTGRESQL_DATABASE=postgresdb
      - POSTGRESQL_USER=postgresadmin
      - POSTGRESQL_PASSWORD=admin123
