apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  # namespace: argocd
data:
  # Enables application status badge feature
  statusbadge.enabled: 'true'

  # Enable plugins so `ksops` can be used to decrypt secrets
  kustomize.buildOptions: "--enable_alpha_plugins"

  # Custom tooling
  configManagementPlugins: |
    - name: env-kustomize
      generate:
        command: [sh, -c]
        args: ["kustomize build --enable_alpha_plugins . |& sed -e 's|$ENV|'$ENV'|g' -e 's|$ARGOCD_APP_SOURCE_TARGET_REVISION|'$ARGOCD_APP_SOURCE_TARGET_REVISION'|g'"]
